apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-app-canary
  labels:
    app: your-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: your-app
      version: canary
  template:
    metadata:
      labels:
        app: your-app
        version: canary
    spec:
      containers:
      - name: your-app
        image: 183991395055.dkr.ecr.us-east-1.amazonaws.com/goapp:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: ecr-secret
