apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-app-canary
  labels:
    app: your-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: your-app
      version: canary
  template:
    metadata:
      labels:
        app: your-app
        version: canary
    spec:
      containers:
      - name: your-app
        image: your-aws-account-id.dkr.ecr.your-region.amazonaws.com/your-repo-name:latest
        ports:
        - containerPort: 8080
